POST http://localhost:3003/api/blogs
Content-Type: application/json

{
	"title": "HTTP cycle",
	"author": "AmineMaila",
	"url": "https://pine-meat-103.notion.site/Walkthrough-of-HTTPS-request-and-response-14abc3b09421804e92b3f2f4764c97c6?pvs=4",
	"likes": 0
}