POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkEtQXJvbiIsImlkIjoiNjgyNGIxZWY1NTdmNmEyY2Y0ODM0MjZkIiwiaWF0IjoxNzQ3MjM4MzA1fQ.TvS8OBk4rwvaVgVu2aN9lPhEq4yhng9mocM3sKe_wvI

{
	"title": "Getting to grips with JavaScript’s prototypal inheritance",
	"author": "Max Powell",
	"url": "https://medium.com/@maxfpowell/getting-to-grips-with-javascripts-prototypal-inheritance-d6cd57ddee59",
	"likes": 50
}